# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f38d8fd795da1075e5c05785b6c9f7eea2aed2b0dab04c3b419ef7214b0dad0bc9150a96096c869ebbc3584170676861e094b677b328c6bcb8230aef33ee63c9

test:
  secret_key_base: fb479fd2442f3167bea94c24dd687dedc863518a285a94ec4a953335bcc24f2b450b9a0e24750f35a8937b819f87ceb9cfce48a9635c8941947fa59d40146b1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
